import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { AuthContextProvider } from '@/contexts/authContext';

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const token = getCookie('auth-token', {req, res});
  // console.log(token);
  return (
    <html lang="pt-br" className={`${roboto.className} dark`}>
      <body className="bg-white dark:bg-black">
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
